//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeIndex.VisualStudioExtension.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeIndex.VisualStudioExtension.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string Health_Error {
            get {
                return ResourceManager.GetString("Health_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Started 的本地化字符串。
        /// </summary>
        public static string Health_Started {
            get {
                return ResourceManager.GetString("Health_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stopped 的本地化字符串。
        /// </summary>
        public static string Health_Stopped {
            get {
                return ResourceManager.GetString("Health_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown 的本地化字符串。
        /// </summary>
        public static string Health_Unknown {
            get {
                return ResourceManager.GetString("Health_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download complete. 的本地化字符串。
        /// </summary>
        public static string Message_DownloadComplete {
            get {
                return ResourceManager.GetString("Message_DownloadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download failed: {0} 的本地化字符串。
        /// </summary>
        public static string Message_DownloadError {
            get {
                return ResourceManager.GetString("Message_DownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extraction failed: {0} 的本地化字符串。
        /// </summary>
        public static string Message_ExtractError {
            get {
                return ResourceManager.GetString("Message_ExtractError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This file is not on your local machine. Do you want to open it in the web portal? 的本地化字符串。
        /// </summary>
        public static string Message_FileNotLocal {
            get {
                return ResourceManager.GetString("Message_FileNotLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Not Found 的本地化字符串。
        /// </summary>
        public static string Message_FileNotLocalTitle {
            get {
                return ResourceManager.GetString("Message_FileNotLocalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings saved successfully. 的本地化字符串。
        /// </summary>
        public static string Message_SaveSuccess {
            get {
                return ResourceManager.GetString("Message_SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server operation failed: {0} 的本地化字符串。
        /// </summary>
        public static string Message_ServerError {
            get {
                return ResourceManager.GetString("Message_ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server started successfully. 的本地化字符串。
        /// </summary>
        public static string Message_ServerStarted {
            get {
                return ResourceManager.GetString("Message_ServerStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server stopped successfully. 的本地化字符串。
        /// </summary>
        public static string Message_ServerStopped {
            get {
                return ResourceManager.GetString("Message_ServerStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to open URL: {0} 的本地化字符串。
        /// </summary>
        public static string Message_UrlOpenError {
            get {
                return ResourceManager.GetString("Message_UrlOpenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Case Sensitive 的本地化字符串。
        /// </summary>
        public static string Search_CaseSensitive {
            get {
                return ResourceManager.GetString("Search_CaseSensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Content 的本地化字符串。
        /// </summary>
        public static string Search_ColumnContent {
            get {
                return ResourceManager.GetString("Search_ColumnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extension 的本地化字符串。
        /// </summary>
        public static string Search_ColumnExtension {
            get {
                return ResourceManager.GetString("Search_ColumnExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Matched Line 的本地化字符串。
        /// </summary>
        public static string Search_ColumnMatchedLine {
            get {
                return ResourceManager.GetString("Search_ColumnMatchedLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string Search_ColumnName {
            get {
                return ResourceManager.GetString("Search_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path 的本地化字符串。
        /// </summary>
        public static string Search_ColumnPath {
            get {
                return ResourceManager.GetString("Search_ColumnPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Content: 的本地化字符串。
        /// </summary>
        public static string Search_Content {
            get {
                return ResourceManager.GetString("Search_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exception Occur: {0} 的本地化字符串。
        /// </summary>
        public static string Search_ExceptionOccur {
            get {
                return ResourceManager.GetString("Search_ExceptionOccur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Extension: 的本地化字符串。
        /// </summary>
        public static string Search_FileExtension {
            get {
                return ResourceManager.GetString("Search_FileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Location: 的本地化字符串。
        /// </summary>
        public static string Search_FileLocation {
            get {
                return ResourceManager.GetString("Search_FileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Name: 的本地化字符串。
        /// </summary>
        public static string Search_FileName {
            get {
                return ResourceManager.GetString("Search_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hint Words: 的本地化字符串。
        /// </summary>
        public static string Search_HintWords {
            get {
                return ResourceManager.GetString("Search_HintWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Index: 的本地化字符串。
        /// </summary>
        public static string Search_Index {
            get {
                return ResourceManager.GetString("Search_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Local server not started. 的本地化字符串。
        /// </summary>
        public static string Search_LocalServerNotStarted {
            get {
                return ResourceManager.GetString("Search_LocalServerNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Local server started, loading indexes... 的本地化字符串。
        /// </summary>
        public static string Search_LocalServerStartedLoadingIndexes {
            get {
                return ResourceManager.GetString("Search_LocalServerStartedLoadingIndexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open settings failed: {0} 的本地化字符串。
        /// </summary>
        public static string Search_OpenSettingsFailed {
            get {
                return ResourceManager.GetString("Search_OpenSettingsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Phase Query 的本地化字符串。
        /// </summary>
        public static string Search_PhaseQuery {
            get {
                return ResourceManager.GetString("Search_PhaseQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search query or index name can&apos;t be empty. 的本地化字符串。
        /// </summary>
        public static string Search_QueryOrIndexEmpty {
            get {
                return ResourceManager.GetString("Search_QueryOrIndexEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh Index 的本地化字符串。
        /// </summary>
        public static string Search_RefreshIndex {
            get {
                return ResourceManager.GetString("Search_RefreshIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Successful: {0}, Desc: {1}, Fetch Count: {2}. 的本地化字符串。
        /// </summary>
        public static string Search_ResultFormat {
            get {
                return ResourceManager.GetString("Search_ResultFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Result Info: 的本地化字符串。
        /// </summary>
        public static string Search_ResultInfo {
            get {
                return ResourceManager.GetString("Search_ResultInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        public static string Search_Search {
            get {
                return ResourceManager.GetString("Search_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search cancelled. 的本地化字符串。
        /// </summary>
        public static string Search_SearchCancelled {
            get {
                return ResourceManager.GetString("Search_SearchCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Searching... 的本地化字符串。
        /// </summary>
        public static string Search_Searching {
            get {
                return ResourceManager.GetString("Search_Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string Search_Settings {
            get {
                return ResourceManager.GetString("Search_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Results: 的本地化字符串。
        /// </summary>
        public static string Search_ShowResults {
            get {
                return ResourceManager.GetString("Search_ShowResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop Search 的本地化字符串。
        /// </summary>
        public static string Search_StopSearch {
            get {
                return ResourceManager.GetString("Search_StopSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Top 100 的本地化字符串。
        /// </summary>
        public static string Search_Top100 {
            get {
                return ResourceManager.GetString("Search_Top100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Top 1000 的本地化字符串。
        /// </summary>
        public static string Search_Top1000 {
            get {
                return ResourceManager.GetString("Search_Top1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Top 10000 的本地化字符串。
        /// </summary>
        public static string Search_Top10000 {
            get {
                return ResourceManager.GetString("Search_Top10000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Top 200 的本地化字符串。
        /// </summary>
        public static string Search_Top200 {
            get {
                return ResourceManager.GetString("Search_Top200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Top 500 的本地化字符串。
        /// </summary>
        public static string Search_Top500 {
            get {
                return ResourceManager.GetString("Search_Top500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse 的本地化字符串。
        /// </summary>
        public static string Settings_Browse {
            get {
                return ResourceManager.GetString("Settings_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Settings_Cancel {
            get {
                return ResourceManager.GetString("Settings_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check 的本地化字符串。
        /// </summary>
        public static string Settings_Check {
            get {
                return ResourceManager.GetString("Settings_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Directory: 的本地化字符串。
        /// </summary>
        public static string Settings_DataDirectory {
            get {
                return ResourceManager.GetString("Settings_DataDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download: 的本地化字符串。
        /// </summary>
        public static string Settings_Download {
            get {
                return ResourceManager.GetString("Settings_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download / Update 的本地化字符串。
        /// </summary>
        public static string Settings_DownloadUpdate {
            get {
                return ResourceManager.GetString("Settings_DownloadUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Health: 的本地化字符串。
        /// </summary>
        public static string Settings_Health {
            get {
                return ResourceManager.GetString("Settings_Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Installed Version: 的本地化字符串。
        /// </summary>
        public static string Settings_InstalledVersion {
            get {
                return ResourceManager.GetString("Settings_InstalledVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Install Path: 的本地化字符串。
        /// </summary>
        public static string Settings_InstallPath {
            get {
                return ResourceManager.GetString("Settings_InstallPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Latest 100 Log Lines 的本地化字符串。
        /// </summary>
        public static string Settings_LatestLogLines {
            get {
                return ResourceManager.GetString("Settings_LatestLogLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Local 的本地化字符串。
        /// </summary>
        public static string Settings_Local {
            get {
                return ResourceManager.GetString("Settings_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Local Server 的本地化字符串。
        /// </summary>
        public static string Settings_LocalServer {
            get {
                return ResourceManager.GetString("Settings_LocalServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Local Service Url: 的本地化字符串。
        /// </summary>
        public static string Settings_LocalServiceUrl {
            get {
                return ResourceManager.GetString("Settings_LocalServiceUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        public static string Settings_Open {
            get {
                return ResourceManager.GetString("Settings_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh Log 的本地化字符串。
        /// </summary>
        public static string Settings_RefreshLog {
            get {
                return ResourceManager.GetString("Settings_RefreshLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remote 的本地化字符串。
        /// </summary>
        public static string Settings_Remote {
            get {
                return ResourceManager.GetString("Settings_Remote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remote Server 的本地化字符串。
        /// </summary>
        public static string Settings_RemoteServer {
            get {
                return ResourceManager.GetString("Settings_RemoteServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remote Service Url: 的本地化字符串。
        /// </summary>
        public static string Settings_RemoteServiceUrl {
            get {
                return ResourceManager.GetString("Settings_RemoteServiceUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restart 的本地化字符串。
        /// </summary>
        public static string Settings_Restart {
            get {
                return ResourceManager.GetString("Settings_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string Settings_Save {
            get {
                return ResourceManager.GetString("Settings_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Local Server Data Directory 的本地化字符串。
        /// </summary>
        public static string Settings_SelectDataDirectory {
            get {
                return ResourceManager.GetString("Settings_SelectDataDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Local Server Install Directory 的本地化字符串。
        /// </summary>
        public static string Settings_SelectInstallDirectory {
            get {
                return ResourceManager.GetString("Settings_SelectInstallDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server Mode 的本地化字符串。
        /// </summary>
        public static string Settings_ServerMode {
            get {
                return ResourceManager.GetString("Settings_ServerMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        public static string Settings_Start {
            get {
                return ResourceManager.GetString("Settings_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop 的本地化字符串。
        /// </summary>
        public static string Settings_Stop {
            get {
                return ResourceManager.GetString("Settings_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CodeIndex Settings 的本地化字符串。
        /// </summary>
        public static string Settings_WindowTitle {
            get {
                return ResourceManager.GetString("Settings_WindowTitle", resourceCulture);
            }
        }
    }
}
