name: Build VSIX on Tag

on:
  push:
    tags:
      - t*

jobs:
  build-vsix:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup MSBuild (add to PATH)
        uses: microsoft/setup-msbuild@v2
      - name: Locate MSBuild
        id: msbuild
        shell: pwsh
        run: |
          # 正确取 ProgramFiles(x86) 需要使用 ${env:ProgramFiles(x86)} 否则路径会变成 "Program Files(x86)"
          $vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
          if(-not (Test-Path $vswhere)) { throw "vswhere not found at $vswhere" }
          $msbuild = & $vswhere -latest -requires Microsoft.Component.MSBuild -find "MSBuild\**\Bin\MSBuild.exe" | Select-Object -First 1
          if(-not $msbuild){ throw 'MSBuild not found' }
          "path=$msbuild" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8
      - name: Build VSIX (Release)
        shell: pwsh
        run: |
          & '${{ steps.msbuild.outputs.path }}' src/CodeIndex.VisualStudioExtension/CodeIndex.VisualStudioExtension.csproj /t:Build /p:Configuration=Release /nologo
      - name: Upload VSIX Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CodeIndex.VisualStudioExtension.vsix
          path: src/CodeIndex.VisualStudioExtension/bin/Release/CodeIndex.VisualStudioExtension.vsix
