name: Build VSIX on Tag

on:
  push:
    tags:
      - t*

jobs:
  build-vsix:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup MSBuild (add to PATH)
        uses: microsoft/setup-msbuild@v2
      - name: Locate MSBuild
        id: msbuild
        shell: pwsh
        run: |
          $vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
          if(-not (Test-Path $vswhere)) { throw "vswhere not found at $vswhere" }
          $msbuild = & $vswhere -latest -requires Microsoft.Component.MSBuild -find "MSBuild\**\Bin\MSBuild.exe" | Select-Object -First 1
          if(-not $msbuild){ throw 'MSBuild not found' }
          "path=$msbuild" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8
      - name: Restore (solution)
        shell: pwsh
        run: |
          dotnet restore src/CodeIndex.VisualStudioExtension/CodeIndex.VisualStudioExtension.sln
      - name: Build VSIX (Release)
        shell: pwsh
        run: |
          & '${{ steps.msbuild.outputs.path }}' src/CodeIndex.VisualStudioExtension/CodeIndex.VisualStudioExtension.csproj /t:Build /p:Configuration=Release /nologo
      - name: Locate VSIX
        id: locate_vsix
        shell: pwsh
        run: |
          $outDir = "src/CodeIndex.VisualStudioExtension/bin/Release"
          if(-not (Test-Path $outDir)) { throw "Output directory not found: $outDir" }
          Write-Host "Listing VSIX output directory contents:"; Get-ChildItem -Path $outDir | Format-Table Name,Length,LastWriteTime
          $vsix = Get-ChildItem -Path $outDir -Filter *.vsix -File | Sort-Object LastWriteTime -Descending | Select-Object -First 1
          if(-not $vsix) {
            Write-Host 'No VSIX found; dumping recursive tree:'
            Get-ChildItem -Path $outDir -Recurse | Select-Object FullName,Length,LastWriteTime | Format-Table -AutoSize
            throw 'VSIX file not generated.'
          }
          Write-Host "Found VSIX: $($vsix.FullName)"
          "path=$($vsix.FullName)" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8
      - name: Upload VSIX Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CodeIndex.VisualStudioExtension.vsix
          path: ${{ steps.locate_vsix.outputs.path }}
